"""
ANTLR-generated Rust parser wrapper.
This module uses the ANTLR-generated RustLexer and RustParser from RustLexer.g4 and RustParser.g4.
Generated by ANTLR 4.13.0
"""

from dataclasses import dataclass
from typing import List, Optional
from antlr4 import InputStream, CommonTokenStream
from antlr4.error.ErrorListener import ErrorListener
from .RustLexer import RustLexer
from .RustParser import RustParser


class SyntaxErrorListener(ErrorListener):
    """Custom error listener for ANTLR to capture syntax errors."""
    
    def __init__(self):
        self.errors: List[str] = []
    
    def syntaxError(self, recognizer, offendingSymbol, line, column, msg, e):
        """Called when ANTLR encounters a syntax error."""
        error_msg = f"Line {line}:{column}: {msg}"
        if offendingSymbol:
            error_msg += f" ('{offendingSymbol.text}')"
        self.errors.append(error_msg)


@dataclass
class ASTNode:
    """Base class for AST nodes."""
    line: int
    column: int


@dataclass
class RustType(ASTNode):
    """Type information."""
    name: str


@dataclass
class Field(ASTNode):
    """Struct field."""
    name: str
    type: RustType


@dataclass
class StructDecl(ASTNode):
    """Struct declaration."""
    name: str
    fields: List[Field]


@dataclass
class Program(ASTNode):
    """Complete program (list of structs)."""
    structs: List[StructDecl]


class ASTBuilder(object):
    """Visitors for ANTLR parse tree to build our AST."""
    
    def visit_program(self, ctx):
        """Visit program context."""
        structs = []
        if ctx.structDecl:
            for struct_ctx in ctx.structDecl():
                struct = self.visit_struct_decl(struct_ctx)
                if struct:
                    structs.append(struct)
        return Program(line=1, column=1, structs=structs)
    
    def visit_struct_decl(self, ctx):
        """Visit struct declaration context."""
        struct_token = ctx.STRUCT()
        if not struct_token:
            return None
        
        ident_token = ctx.IDENT()
        if not ident_token:
            return None
        
        struct_name = ident_token.getText()
        line = struct_token.symbol.line
        column = struct_token.symbol.column
        
        fields = []
        fields_ctx = ctx.fields()
        if fields_ctx:
            fields = self.visit_fields(fields_ctx)
        
        return StructDecl(
            line=line,
            column=column,
            name=struct_name,
            fields=fields
        )
    
    def visit_fields(self, ctx):
        """Visit fields context."""
        fields = []
        if ctx.field:
            for field_ctx in ctx.field():
                field = self.visit_field(field_ctx)
                if field:
                    fields.append(field)
        return fields
    
    def visit_field(self, ctx):
        """Visit field context."""
        ident_token = ctx.IDENT()
        if not ident_token:
            return None
        
        field_name = ident_token.getText()
        line = ident_token.symbol.line
        column = ident_token.symbol.column
        
        type_ctx = ctx.type_()
        rust_type = self.visit_type(type_ctx) if type_ctx else None
        
        if rust_type:
            return Field(
                line=line,
                column=column,
                name=field_name,
                type=rust_type
            )
        return None
    
    def visit_type(self, ctx):
        """Visit type context."""
        # Get the text of the type
        type_text = ctx.getText()
        line = ctx.start.line if ctx.start else 1
        column = ctx.start.column if ctx.start else 1
        
        return RustType(
            line=line,
            column=column,
            name=type_text
        )


class AntlrRustLexer:
    """Wrapper for ANTLR-generated RustLexer."""
    
    def __init__(self, text: str):
        self.text = text
        self.errors: List[str] = []
        self.lexer = None
        self.stream = None
    
    def tokenize(self):
        """Tokenize input using ANTLR lexer, return token stream."""
        # Create input stream from text
        input_stream = InputStream(self.text)
        
        # Create lexer
        self.lexer = RustLexer(input_stream)
        
        # Create token stream
        self.stream = CommonTokenStream(self.lexer)
        self.stream.fill()
        
        # Capture lexer errors
        self.lexer.removeErrorListeners()
        error_listener = SyntaxErrorListener()
        self.lexer.addErrorListener(error_listener)
        
        self.errors = error_listener.errors
        
        return self.stream


class AntlrRustParser:
    """Wrapper for ANTLR-generated RustParser."""
    
    def __init__(self, token_stream):
        self.token_stream = token_stream
        self.errors: List[str] = []
    
    def parse(self) -> Program:
        """Parse tokens using ANTLR parser."""
        # Create parser from token stream
        parser = RustParser(self.token_stream)
        
        # Capture parser errors
        parser.removeErrorListeners()
        error_listener = SyntaxErrorListener()
        parser.addErrorListener(error_listener)
        
        # Parse program
        program_ctx = parser.program()
        
        self.errors = error_listener.errors
        
        # Build AST from parse tree
        builder = ASTBuilder()
        ast = builder.visit_program(program_ctx)
        
        return ast
